# Generated by Django 6.0.3 on 2026-03-23 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('tenant_id', 'name'), name='unique_tenant_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('U', 'Unit')], default='U', max_length=5)),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['barcode'], name='idx_product_barcode')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('tenant_id', 'name'), name='unique_tenant_product_name'), models.UniqueConstraint(condition=models.Q(('active', True), models.Q(('barcode', ''), _negated=True)), fields=('tenant_id', 'barcode'), name='unique_tenant_product_barcode')],
            },
        ),
    ]
