# Generated by Django 6.0.3 on 2026-03-23 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'sale_details',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cashbox.cashbox')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
    ]
