# Generated by Django 6.0.3 on 2026-03-23 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes_opened', to=settings.AUTH_USER_MODEL),
        ),
    ]
