# Generated by Django 6.0.3 on 2026-08-25 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cash_registers',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'name'), name='cash_register_unique_tenant_name')],
            },
        ),
        migrations.AddField(
            model_name='cashbox',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes', to='cashbox.cashregister'),
        ),
        migrations.AddConstraint(
            model_name='cashbox',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('register',), name='cashbox_unique_open_register'),
        ),
        migrations.AddConstraint(
            model_name='cashbox',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('opened_by',), name='cashbox_unique_open_user'),
        ),
    ]
