import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("sales", "0004_sale_mercado_pago_choices")]
    operations = [
        migrations.CreateModel(
            name="MercadoPagoBillingRelease",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(db_index=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "mercado_pago_billing_releases"},
        ),
        migrations.CreateModel(
            name="MercadoPagoWebhookInbox",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notification_key", models.CharField(max_length=64, unique=True)),
                ("request_id", models.CharField(max_length=160)),
                ("data_id", models.CharField(db_index=True, max_length=160)),
                ("topic", models.CharField(blank=True, max_length=80)),
                ("action", models.CharField(blank=True, max_length=120)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("PROCESSING", "Processing"), ("RETRYING", "Retrying"), ("PROCESSED", "Processed"), ("IGNORED", "Ignored"), ("FAILED", "Failed")], db_index=True, default="PENDING", max_length=20)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "mercado_pago_webhook_inbox"},
        ),
        migrations.CreateModel(
            name="MercadoPagoOrder",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("order_type", models.CharField(choices=[("POINT", "Point"), ("QR", "Dynamic QR")], max_length=10)),
                ("state", models.CharField(choices=[("CREATING", "Creating"), ("PENDING", "Pending"), ("PAID", "Paid"), ("CANCEL_REQUESTED", "Cancel requested"), ("ACTION_REQUIRED", "Terminal action required"), ("REFUND_PENDING", "Refund pending"), ("CANCELLED", "Cancelled"), ("FAILED", "Failed"), ("EXPIRED", "Expired"), ("REFUNDED", "Refunded"), ("ERROR", "Temporary error")], db_index=True, default="CREATING", max_length=30)),
                ("remote_status", models.CharField(blank=True, max_length=80)),
                ("remote_status_detail", models.CharField(blank=True, max_length=160)),
                ("external_order_id", models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ("external_reference", models.CharField(max_length=160)),
                ("collector_id", models.CharField(blank=True, max_length=120)),
                ("currency", models.CharField(default="ARS", max_length=8)),
                ("live_mode", models.BooleanField(default=False)),
                ("terminal_id", models.CharField(blank=True, max_length=120, null=True)),
                ("pos_id", models.CharField(blank=True, max_length=120, null=True)),
                ("external_pos_id", models.CharField(blank=True, max_length=120, null=True)),
                ("frontend_idempotency_key", models.CharField(max_length=200)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("create_idempotency_key", models.CharField(max_length=200)),
                ("cancel_idempotency_key", models.CharField(blank=True, max_length=200)),
                ("refund_idempotency_key", models.CharField(blank=True, max_length=200)),
                ("billing_reservation_key", models.CharField(max_length=200)),
                ("billing_reservation_id", models.CharField(blank=True, max_length=160)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("qr_data", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("reconcile_version", models.PositiveBigIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_message", models.TextField(blank=True)),
                ("stock_restored", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sale", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="mercado_pago_order", to="sales.sale")),
            ],
            options={"db_table": "mercado_pago_orders"},
        ),
        migrations.AddIndex(model_name="mercadopagowebhookinbox", index=models.Index(fields=["status", "next_attempt_at"], name="mp_webhook_due_idx")),
        migrations.AddIndex(model_name="mercadopagobillingrelease", index=models.Index(fields=["next_attempt_at", "locked_at"], name="mp_bill_release_due_idx")),
        migrations.AddIndex(model_name="mercadopagoorder", index=models.Index(fields=["state", "next_retry_at"], name="mp_order_due_idx")),
        migrations.AddConstraint(model_name="mercadopagoorder", constraint=models.UniqueConstraint(fields=("tenant_id", "frontend_idempotency_key"), name="mp_order_uq_tenant_front_key")),
    ]
