"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga el .env en os.environ (solo vars que no estén ya definidas en el proceso)
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    with open(_env_file) as _f:
        for _line in _f:
            _line = _line.strip()
            if not _line or _line.startswith('#') or '=' not in _line:
                continue
            _k, _, _v = _line.partition('=')
            _k = _k.strip()
            _v = _v.split('#')[0].strip()
            if _k and _k not in os.environ:
                os.environ[_k] = _v


def env_bool(name, default="False"):
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-w$%ltt_)i(xmc9pmop=yevl2y!2oay8ea3t9xpg_)z6gf0c$0g',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', 'True')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]
CSRF_TRUSTED_ORIGINS = [
    h.strip()
    for h in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if h.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_filters',
    'drf_spectacular',

    'apps.users',
    'apps.products',
    'apps.sales',
    'apps.cashbox',
    'apps.reports',
    'apps.audit',
    'apps.suppliers',
    'apps.tenants',
    'apps.notifications',
    'apps.document_extractor',
    'apps.platform_billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.tenant.TenantMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'POSTAS API',
    'DESCRIPTION': 'API para sistema de punto de venta (POS) multi-tenant',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Auth', 'description': 'Login y refresh de tokens JWT'},
        {'name': 'Users', 'description': 'CRUD de usuarios (solo OWNER)'},
        {'name': 'Categories', 'description': 'CRUD de categorias de productos'},
        {'name': 'Products', 'description': 'CRUD de productos y busqueda'},
        {'name': 'Cashbox', 'description': 'Apertura, cierre y consulta de cajas'},
        {'name': 'Sales', 'description': 'Registro, consulta y anulacion de ventas'},
        {'name': 'Reports', 'description': 'Reportes de ventas, productos y cajas'},
        {'name': 'Audit', 'description': 'Logs de auditoria'},
        {'name': 'Suppliers', 'description': 'CRUD de proveedores y relaciones producto-proveedor'},
        {'name': 'TenantConfig', 'description': 'Configuracion del tenant'},
        {'name': 'DocumentExtractor', 'description': 'Extraccion de productos desde documentos con IA'},
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'apps.users.authentication.CustomTokenObtainPairSerializer',
    'USER_ID_FIELD': 'uuid',
    'USER_ID_CLAIM': 'user_id',
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url


def _database_url():
    configured_url = os.getenv('DATABASE_URL', '').strip()
    if configured_url:
        return configured_url

    return f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}"


DATABASES = {
    'default': dj_database_url.parse(
        _database_url(),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'


# Email
EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "resend").strip().lower()
EMAIL_FALLBACK_PROVIDER = os.getenv("EMAIL_FALLBACK_PROVIDER", "django").strip().lower()
EMAIL_PROVIDER_FALLBACK_ENABLED = env_bool("EMAIL_PROVIDER_FALLBACK_ENABLED", "True")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", "True")
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", "False")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "POSTAS <noreply@postas.app>")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "20"))
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_API_URL = os.getenv("RESEND_API_URL", "https://api.resend.com")
RESEND_COST_PER_1000_EMAILS = os.getenv("RESEND_COST_PER_1000_EMAILS", "0.90")
DJANGO_EMAIL_COST_PER_1000_EMAILS = os.getenv("DJANGO_EMAIL_COST_PER_1000_EMAILS", "0")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# Internal platform billing / plan entitlements
POSTAS_PLATFORM_API_URL = os.getenv("POSTAS_PLATFORM_API_URL", "http://localhost:8001").rstrip("/")
POSTAS_PLATFORM_SERVICE_TOKEN = os.getenv("POSTAS_PLATFORM_SERVICE_TOKEN", "")
POSTAS_PLATFORM_SOURCE = os.getenv("POSTAS_PLATFORM_SOURCE", "postas_api")
POSTAS_PLATFORM_TIMEOUT_SECONDS = int(os.getenv("POSTAS_PLATFORM_TIMEOUT_SECONDS", "10"))

# Cloudflare R2 / S3
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME", "")
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
R2_REGION = os.getenv("R2_REGION", "auto")
R2_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL", "")
R2_PUBLIC_URL = os.getenv("R2_PUBLIC_URL", "")
R2_ALLOWED_EXTENSIONS = tuple(os.getenv("R2_ALLOWED_EXTENSIONS", ".jpg,.jpeg,.png,.webp").split(","))
R2_MAX_IMAGE_SIZE = int(os.getenv("R2_MAX_IMAGE_SIZE", str(5 * 1024 * 1024)))

# Document extractor / IA API
AI_EXTRACTOR_BASE_URL = os.getenv("AI_EXTRACTOR_BASE_URL", "http://localhost:8001/api/v1")
AI_EXTRACTOR_TOKEN = os.getenv("AI_EXTRACTOR_TOKEN", "")
AI_EXTRACTOR_SOURCE = os.getenv("AI_EXTRACTOR_SOURCE", "postas_api")
AI_EXTRACTOR_TIMEOUT = int(os.getenv("AI_EXTRACTOR_TIMEOUT", "90"))
DOCUMENT_EXTRACTOR_ALLOWED_EXTENSIONS = tuple(
    ext.strip().lower()
    for ext in os.getenv("DOCUMENT_EXTRACTOR_ALLOWED_EXTENSIONS", ".jpg,.jpeg,.png").split(",")
    if ext.strip()
)
DOCUMENT_EXTRACTOR_MAX_IMAGE_SIZE = int(os.getenv("DOCUMENT_EXTRACTOR_MAX_IMAGE_SIZE", str(R2_MAX_IMAGE_SIZE)))
DOCUMENT_EXTRACTOR_PRESIGNED_URL_TTL = int(os.getenv("DOCUMENT_EXTRACTOR_PRESIGNED_URL_TTL", "600"))
DOCUMENT_EXTRACTOR_ACCEPTED_CONFIDENCE = float(os.getenv("DOCUMENT_EXTRACTOR_ACCEPTED_CONFIDENCE", "0.85"))
DOCUMENT_EXTRACTOR_MIN_CONFIDENCE = float(os.getenv("DOCUMENT_EXTRACTOR_MIN_CONFIDENCE", "0.60"))
