# Generated by Django 6.0.3 on 2026-03-23 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('SALE', 'Sale'), ('CASHBOX', 'Cashbox')], max_length=20)),
                ('entity', models.CharField(choices=[('USER', 'User'), ('PRODUCT', 'Product'), ('CATEGORY', 'Category'), ('SALE', 'Sale'), ('CASHBOX', 'Cashbox')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
