# Generated by Django 6.0.3 on 2026-05-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('SALE', 'Sale'), ('CASHBOX', 'Cashbox'), ('CASHBOX_EMAIL', 'Cashbox email'), ('CASHBOX_EMAIL_SKIP', 'Cashbox email skipped'), ('CASHBOX_EMAIL_FAILED', 'Cashbox email failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity',
            field=models.CharField(choices=[('USER', 'User'), ('PRODUCT', 'Product'), ('CATEGORY', 'Category'), ('SALE', 'Sale'), ('CASHBOX', 'Cashbox'), ('TENANT_CONFIG', 'Tenant config')], max_length=20),
        ),
    ]
