# Generated by Django 6.0.3 on 2026-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action_alter_auditlog_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity',
            field=models.CharField(choices=[('USER', 'User'), ('PRODUCT', 'Product'), ('CATEGORY', 'Category'), ('SALE', 'Sale'), ('CASHBOX', 'Cashbox'), ('CASH_REGISTER', 'Cash register'), ('TENANT_CONFIG', 'Tenant config')], max_length=20),
        ),
    ]
