# Generated by Django 6.0.3 on 2026-05-25 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notification_type', models.CharField(choices=[('cashbox_opened', 'Cashbox opened'), ('cashbox_closed', 'Cashbox closed'), ('password_reset', 'Password reset'), ('debug', 'Debug')], max_length=50)),
                ('provider', models.CharField(choices=[('resend', 'Resend'), ('django', 'Django email backend')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_emails', models.JSONField(default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('related_entity', models.CharField(blank=True, max_length=80)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_email_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='notificatio_tenant__578ffd_idx'), models.Index(fields=['provider', 'status'], name='notificatio_provide_aa9107_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_28e1e3_idx')],
            },
        ),
    ]
